# Generated by Django 4.1.6 on 2023-02-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoG', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Videog',
        ),
    ]
