# Generated by Django 4.1.6 on 2023-02-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoG', '0002_rename_todo_videog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videog',
            old_name='details',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='videog',
            old_name='subject',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='videog',
            name='image',
            field=models.CharField(default='https://developers.elementor.com/docs/assets/img/elementor-placeholder-image.png', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videog',
            name='rating',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videog',
            name='title',
            field=models.CharField(default='text', max_length=100),
            preserve_default=False,
        ),
    ]
